Country top
surftimer/SurfTimer pull request #484
Opened 2022-07-29 02:50 UTC by shipyy

# Allow player's to see the leaderboards of any country in every style

## sm_ctop
![image](https://user-images.githubusercontent.com/70631212/181671302-2f9c9cb7-d807-4d1e-9b2b-e6ce7ea4e8ab.png)
![image](https://user-images.githubusercontent.com/70631212/181671338-cca77362-bac7-4ffe-aa30-7e2f899f03aa.png)

## sm_crank
![image](https://user-images.githubusercontent.com/70631212/181671388-77508dbc-5a2f-44e6-a718-c9d52a199ac1.png)

allows multiple inputs aswell i.e :
` sm_crank <playername> `
` sm_crank <style> `
` sm_crank <playername> <style> `
` sm_crank <style> <playername> `

2022-07-29 07:03 UTC, tslashd commented
For some reason it's saying the players are from Bulgaria in chat, but they are not:
![crank country](https://user-images.githubusercontent.com/74899888/181701488-19761a33-f0cc-4ece-b935-ec4281d15bcb.png)


`sm_crank <style>` - seems to not work for all styles and it works only if you type the full string of the style (got it to print something for `Freestyle, Low-Gravity, Normal` nothing else)

`<style>` var if possible should be able to use abbreviations (`Freestyle = FS; Low-Gravity = LG; Half-Sideways = HSW;` etc.) for the styles as currently you need to write the whole style name like I have shown above.
Almost nobody knows the `int` corresponding to the style in order to use that

2022-08-05 14:17 UTC, Bara requested changes

2022-08-05 14:17 UTC, Bara commented on addons/sourcemod/scripting/surftimer/commands.sp
> +				ArrayList styles = new ArrayList(32);
ArrayList must be deleted, otherwise you'll run sometime into an memory leak.

2022-08-05 14:17 UTC, Bara commented on addons/sourcemod/scripting/surftimer/commands.sp
> +	Format(szItem, sizeof(szItem), "Normal");
We could loop `g_EditStyles` here, or? Would save us some lines of code.

2022-08-05 15:38 UTC, Bara approved these changes
Would be nice if someone could test this ( @tslashd maybe? )

2022-08-05 16:00 UTC, tslashd commented
> Would be nice if someone could test this ( @tslashd maybe? )

Missing `}` in [translation](https://github.com/shipyy/Surftimer-Official/blob/b38fe9a60aacff5c6aa2d8a4f7a3fb3ade5361ea/addons/sourcemod/translations/surftimer.phrases.txt#L1872) file was throwing error.
Other than than all seems good

2022-08-05 18:25 UTC, merged