Fix Replays with CP selected
surftimer/SurfTimer pull request #498
Opened 2022-08-09 23:55 UTC by shipyy

error occuring before 
![image](https://user-images.githubusercontent.com/70631212/183781186-abf0dccc-4f66-4a20-93c9-8f3cf45f94ab.png)

was due to wrong query format resulting in a false positive regarding duplicate entry

added a check to not display the starting points from replay incase there was no replay cp ticks found when loading

also swapped multiple queries to a unique transaction instead

2022-08-10 07:30 UTC, tslashd commented
Error seems to not be present after this.

_Before this fix the replay from the map mentioned in PR has been replaced by a non WR tho_

2022-08-10 08:34 UTC, Bara requested changes

2022-08-10 08:34 UTC, Bara commented on addons/sourcemod/scripting/surftimer/sql.sp
> +	SQL_ExecuteTransaction(g_hDb, TicksTransaction, db_TicksTransactionOnSuccess, db_TicksTransactionOnFailure, DBPrio_Low);
DBPrio_Low is here wrong. Replace it with this:
`SQL_ExecuteTransaction(g_hDb, TicksTransaction, db_TicksTransactionOnSuccess, db_TicksTransactionOnFailure, _, DBPrio_Low);`

2022-08-10 08:35 UTC, Bara commented on addons/sourcemod/scripting/surftimer/sql.sp
> +	SQL_ExecuteTransaction(g_hDb, TicksTransaction, db_TicksTransactionOnSuccess, db_TicksTransactionOnFailure, DBPrio_Low);
or `.priority=DBPrio_Low` works too

2022-08-11 22:21 UTC, tslashd commented
does not update CPs in chat until reconnecting to the server

2022-08-12 17:02 UTC, shipyy commented
the errors related to ck_checkpoints were happening because the changes were not merged from the other PR(#499 ) that fixes taht issue

2022-08-12 20:28 UTC, Bara approved these changes

2022-08-12 20:28 UTC, merged